// bundle-size-compare/lit-bundle/src/MyButton.ts
import { LitElement, html, css } from "lit";
import { customElement, property, state } from "lit/decorators.js";

@customElement("my-button")
export class MyButton extends LitElement {
  @property({ type: String }) label = "Click me";
  @state() private count = 0;

  static styles = css`
    button {
      background: blue;
      color: white;
      padding: 0.5rem 1rem;
    }
  `;

  updated(changedProperties: Map<string, unknown>) {
    if (changedProperties.has("count")) {
      console.log(`Clicked ${this.count} times`);
    }
  }

  private handleClick() {
    this.count += 1;
  }

  render() {
    return html`
      <button @click=${this.handleClick}>${this.label} (${this.count})</button>
    `;
  }
}

// bundle-size-compare/react-bundle/src/MyButton.tsx
import { useState, useEffect } from "react";

export const MyButton = ({ label = "Click me" }: { label?: string }) => {
  const [count, setCount] = useState(0);

  useEffect(() => {
    console.log(`Clicked ${count} times`);
  }, [count]);

  return (
    <button
      style={{ background: "blue", color: "white", padding: "0.5rem 1rem" }}
      onClick={() => setCount((c) => c + 1)}
    >
      {label} ({count})
    </button>
  );
};
